[package]
name = "webhook_manager"
version = "1.0.1"
edition = "2024"

[dev-dependencies]
serial_test = "3.4.0"

[dependencies]
async-trait = "0.1.86"
anyhow = "1.0.29"
config = "0.15.23"
derive_builder = "0.20.2"
dotenv = "0.15.0"
metrics-exporter-prometheus = "0.17.0"
axum-prometheus = "0.8.0"
axum-tracing-opentelemetry = "0.29.0"
thiserror = "2.0.12"
serde_json = "1.0.140"
getset = "0.1.5"
tracing = "0.1"
serde_derive = "1.0.218"
regex = "1.11.1"
tracing-loki = "0.2.6"
tracing-subscriber = "0.3.19"
console-subscriber = "0.5.0"


[dependencies.chrono]
version = "0.4.41"
features = ["serde"]

[dependencies.tokio]
version = "1.52.3"
features = ["full"]

[dependencies.tower-http]
version = "0.7.0"
features = ["trace", "cors"]

[dependencies.utoipa]
version = "5.5.0"
features = ["axum_extras", "chrono"]

[dependencies.utoipa-swagger-ui]
version = "9"
features = ["axum"] 

[dependencies.uuid]
version = "1.23.3"
features = [
    "v4", 
    "serde"
]

[dependencies.redis]
version = "1.2.3"
features = ["aio", "tokio-comp", "connection-manager", "json"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.axum]
version = "0.8.4"
features = ["ws"]

[dependencies.reqwest]
version = "0.12.19"
features = ["json"] 




